### ISSUE TITLE
build on ubuntu arm64 Cannot install gcc-multilib

### ISSUE THREAD

**Issue by DannyAtVodooTH** [friendlyarm/build-env-on-ubuntu-bionic#5]
trying to build on mac m1 with ubuntu results in  error 

```
sudo apt-get install gcc-multilib

but I got the following error message:
=========================================
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package gcc-multilib is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
```

Is there a solution for this?

**Comment by lawrencetg** [comment]
The script in this repository only support amd64 host, m1 is arm64.
However, you can use orb to create an x86 virtual machine under m1, but the performance will decrease.

**Comment by DannyAtVodooTH** [comment]
@lawrencetg thanks for the feedback, yes that's how i'm running it now on UTM virtualization of x64 on arm64.
I'm looking for some performance boost to run native on arm.

would it be correct to presume i would need to build the sdk for arm?
Is the source for such build availleble?
Br,
Danny

**Comment by lawrencetg** [comment]
Using the script provided in the repository link below, you can compile the kernel and package the firmware on arm64, but you cannot compile u-boot. However, it is sufficient for most people to use:
https://github.com/friendlyarm/sd-fuse_rk3588

I don't know what SDK you need to compile. If it doesn't involve U-Boot compilation, most things can be done on ARM64.

**Comment by dgoo2308** [comment]
Thanks,

only need to build packages, not u-boot

Br,
Danny
